/**
 * trackme.lk API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package lk.trackme.client.model;

import java.util.*;
import lk.trackme.client.model.User;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Device {
  
  @SerializedName("speedLimit")
  private Double speedLimit = null;
  public enum IconTypeEnum {
     DEFAULT,  PHONE,  BICYCLE,  SEDAN,  UNIVERSAL,  MINIVAN,  TRUCK,  BUS,  LONG_TRUCK,  CAR_TRUCK,  PLANE,  SHIP,  TRAIN, 
  };
  @SerializedName("iconType")
  private IconTypeEnum iconType = null;
  @SerializedName("users")
  private List<User> users = null;
  @SerializedName("owner")
  private User owner = null;
  @SerializedName("id")
  private Long id = null;
  @SerializedName("unique_id")
  private String uniqueId = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("phone_number")
  private String phoneNumber = null;
  @SerializedName("plate_number")
  private String plateNumber = null;
  @SerializedName("vehicle_info")
  private String vehicleInfo = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getSpeedLimit() {
    return speedLimit;
  }
  public void setSpeedLimit(Double speedLimit) {
    this.speedLimit = speedLimit;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public IconTypeEnum getIconType() {
    return iconType;
  }
  public void setIconType(IconTypeEnum iconType) {
    this.iconType = iconType;
  }

  /**
   * Users, who have access to this device
   **/
  @ApiModelProperty(value = "Users, who have access to this device")
  public List<User> getUsers() {
    return users;
  }
  public void setUsers(List<User> users) {
    this.users = users;
  }

  /**
   * User, who owns device
   **/
  @ApiModelProperty(value = "User, who owns device")
  public User getOwner() {
    return owner;
  }
  public void setOwner(User owner) {
    this.owner = owner;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  /**
   * Device's unique identifier (for example IMEI)
   **/
  @ApiModelProperty(value = "Device's unique identifier (for example IMEI)")
  public String getUniqueId() {
    return uniqueId;
  }
  public void setUniqueId(String uniqueId) {
    this.uniqueId = uniqueId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * Number of installed SIM card
   **/
  @ApiModelProperty(value = "Number of installed SIM card")
  public String getPhoneNumber() {
    return phoneNumber;
  }
  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  /**
   * Number of plate
   **/
  @ApiModelProperty(value = "Number of plate")
  public String getPlateNumber() {
    return plateNumber;
  }
  public void setPlateNumber(String plateNumber) {
    this.plateNumber = plateNumber;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getVehicleInfo() {
    return vehicleInfo;
  }
  public void setVehicleInfo(String vehicleInfo) {
    this.vehicleInfo = vehicleInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Device device = (Device) o;
    return (this.speedLimit == null ? device.speedLimit == null : this.speedLimit.equals(device.speedLimit)) &&
        (this.iconType == null ? device.iconType == null : this.iconType.equals(device.iconType)) &&
        (this.users == null ? device.users == null : this.users.equals(device.users)) &&
        (this.owner == null ? device.owner == null : this.owner.equals(device.owner)) &&
        (this.id == null ? device.id == null : this.id.equals(device.id)) &&
        (this.uniqueId == null ? device.uniqueId == null : this.uniqueId.equals(device.uniqueId)) &&
        (this.name == null ? device.name == null : this.name.equals(device.name)) &&
        (this.description == null ? device.description == null : this.description.equals(device.description)) &&
        (this.phoneNumber == null ? device.phoneNumber == null : this.phoneNumber.equals(device.phoneNumber)) &&
        (this.plateNumber == null ? device.plateNumber == null : this.plateNumber.equals(device.plateNumber)) &&
        (this.vehicleInfo == null ? device.vehicleInfo == null : this.vehicleInfo.equals(device.vehicleInfo));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.speedLimit == null ? 0: this.speedLimit.hashCode());
    result = 31 * result + (this.iconType == null ? 0: this.iconType.hashCode());
    result = 31 * result + (this.users == null ? 0: this.users.hashCode());
    result = 31 * result + (this.owner == null ? 0: this.owner.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.uniqueId == null ? 0: this.uniqueId.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.phoneNumber == null ? 0: this.phoneNumber.hashCode());
    result = 31 * result + (this.plateNumber == null ? 0: this.plateNumber.hashCode());
    result = 31 * result + (this.vehicleInfo == null ? 0: this.vehicleInfo.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Device {\n");
    
    sb.append("  speedLimit: ").append(speedLimit).append("\n");
    sb.append("  iconType: ").append(iconType).append("\n");
    sb.append("  users: ").append(users).append("\n");
    sb.append("  owner: ").append(owner).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  uniqueId: ").append(uniqueId).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  phoneNumber: ").append(phoneNumber).append("\n");
    sb.append("  plateNumber: ").append(plateNumber).append("\n");
    sb.append("  vehicleInfo: ").append(vehicleInfo).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
