/**
 * trackme.lk API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package lk.trackme.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class UserSettings {
  
  @SerializedName("maximizeOverviewMap")
  private Boolean maximizeOverviewMap = null;
  @SerializedName("id")
  private Long id = null;
  public enum SpeedUnitEnum {
     knots,  kilometersPerHour,  milesPerHour, 
  };
  @SerializedName("speed_unit")
  private SpeedUnitEnum speedUnit = null;
  @SerializedName("timezone_id")
  private String timezoneId = null;
  @SerializedName("zoom_level")
  private Integer zoomLevel = null;
  @SerializedName("center_longitude")
  private Double centerLongitude = null;
  @SerializedName("center_latitude")
  private Double centerLatitude = null;
  public enum MapTypeEnum {
     OSM,  GOOGLE_HYBRID,  GOOGLE_NORMAL,  GOOGLE_SATELLITE,  GOOGLE_TERRAIN,  BING_ROAD,  BING_HYBRID,  BING_AERIAL,  MAPQUEST_ROAD,  MAPQUEST_AERIAL,  STAMEN_TONER, 
  };
  @SerializedName("map_type")
  private MapTypeEnum mapType = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getMaximizeOverviewMap() {
    return maximizeOverviewMap;
  }
  public void setMaximizeOverviewMap(Boolean maximizeOverviewMap) {
    this.maximizeOverviewMap = maximizeOverviewMap;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  /**
   * Default units of speed shown on map
   **/
  @ApiModelProperty(value = "Default units of speed shown on map")
  public SpeedUnitEnum getSpeedUnit() {
    return speedUnit;
  }
  public void setSpeedUnit(SpeedUnitEnum speedUnit) {
    this.speedUnit = speedUnit;
  }

  /**
   * User's timezone ID
   **/
  @ApiModelProperty(value = "User's timezone ID")
  public String getTimezoneId() {
    return timezoneId;
  }
  public void setTimezoneId(String timezoneId) {
    this.timezoneId = timezoneId;
  }

  /**
   * Default level of zoom on map
   **/
  @ApiModelProperty(value = "Default level of zoom on map")
  public Integer getZoomLevel() {
    return zoomLevel;
  }
  public void setZoomLevel(Integer zoomLevel) {
    this.zoomLevel = zoomLevel;
  }

  /**
   * Longitude of map center opened by default
   **/
  @ApiModelProperty(value = "Longitude of map center opened by default")
  public Double getCenterLongitude() {
    return centerLongitude;
  }
  public void setCenterLongitude(Double centerLongitude) {
    this.centerLongitude = centerLongitude;
  }

  /**
   * Longitude of map center opened by default
   **/
  @ApiModelProperty(value = "Longitude of map center opened by default")
  public Double getCenterLatitude() {
    return centerLatitude;
  }
  public void setCenterLatitude(Double centerLatitude) {
    this.centerLatitude = centerLatitude;
  }

  /**
   * Type of map opened by default
   **/
  @ApiModelProperty(value = "Type of map opened by default")
  public MapTypeEnum getMapType() {
    return mapType;
  }
  public void setMapType(MapTypeEnum mapType) {
    this.mapType = mapType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserSettings userSettings = (UserSettings) o;
    return (this.maximizeOverviewMap == null ? userSettings.maximizeOverviewMap == null : this.maximizeOverviewMap.equals(userSettings.maximizeOverviewMap)) &&
        (this.id == null ? userSettings.id == null : this.id.equals(userSettings.id)) &&
        (this.speedUnit == null ? userSettings.speedUnit == null : this.speedUnit.equals(userSettings.speedUnit)) &&
        (this.timezoneId == null ? userSettings.timezoneId == null : this.timezoneId.equals(userSettings.timezoneId)) &&
        (this.zoomLevel == null ? userSettings.zoomLevel == null : this.zoomLevel.equals(userSettings.zoomLevel)) &&
        (this.centerLongitude == null ? userSettings.centerLongitude == null : this.centerLongitude.equals(userSettings.centerLongitude)) &&
        (this.centerLatitude == null ? userSettings.centerLatitude == null : this.centerLatitude.equals(userSettings.centerLatitude)) &&
        (this.mapType == null ? userSettings.mapType == null : this.mapType.equals(userSettings.mapType));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.maximizeOverviewMap == null ? 0: this.maximizeOverviewMap.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.speedUnit == null ? 0: this.speedUnit.hashCode());
    result = 31 * result + (this.timezoneId == null ? 0: this.timezoneId.hashCode());
    result = 31 * result + (this.zoomLevel == null ? 0: this.zoomLevel.hashCode());
    result = 31 * result + (this.centerLongitude == null ? 0: this.centerLongitude.hashCode());
    result = 31 * result + (this.centerLatitude == null ? 0: this.centerLatitude.hashCode());
    result = 31 * result + (this.mapType == null ? 0: this.mapType.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserSettings {\n");
    
    sb.append("  maximizeOverviewMap: ").append(maximizeOverviewMap).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  speedUnit: ").append(speedUnit).append("\n");
    sb.append("  timezoneId: ").append(timezoneId).append("\n");
    sb.append("  zoomLevel: ").append(zoomLevel).append("\n");
    sb.append("  centerLongitude: ").append(centerLongitude).append("\n");
    sb.append("  centerLatitude: ").append(centerLatitude).append("\n");
    sb.append("  mapType: ").append(mapType).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
